import { useEffect, useState } from "react"
export default function Dashboard(){
  const [me,setMe]=useState<any>(null); const [wfs,setWfs]=useState<any[]>([]); const [tenants,setTenants]=useState<any[]>([]); const [noteText,setNoteText]=useState<{[key:string]:string}>({})
  useEffect(()=>{
    const m = JSON.parse(localStorage.getItem("user")||"null"); if(!m){ location.href="/"; return }; setMe(m)
    fetch("/api/tenants").then(r=>r.json()).then(d=>setTenants(d.tenants||[]))
    const url = m.role==="SUPER_ADMIN"? "/api/workflows" : `/api/workflows?companyId=${m.companyId}`
    fetch(url).then(r=>r.json()).then(d=>setWfs(d.workflows||[]))
  },[])
  const companyName = tenants.find(t=>t.id===me?.companyId)?.name || me?.companyId
  const isSuper = me?.role==="SUPER_ADMIN"
  const addNote=async(wfId:string)=>{ const text = noteText[wfId]; if(!text) return; await fetch(`/api/workflows?id=${wfId}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:wfId, note:text})}); setNoteText({...noteText, [wfId]:""}); const url = me.role==="SUPER_ADMIN"? "/api/workflows" : `/api/workflows?companyId=${me.companyId}`; fetch(url).then(r=>r.json()).then(d=>setWfs(d.workflows||[])) }
  const printWorkflow=(w:any)=>{
    const html = `<html><head><title>${w.name}</title><style>body{font-family:Arial;padding:40px;color:#222}.header{border-bottom:3px solid #ff7a00;padding-bottom:15px} h1{color:#0a0a0f} table{width:100%;border-collapse:collapse;margin-top:20px} th,td{border:1px solid #ddd;padding:10px} th{background:#f5f5f5}</style></head><body><div class=header><h1>Production Sheet</h1><h2>${w.name}</h2><p>Company: ${companyName} | Status: ${w.status} | Date: ${new Date().toLocaleString()}</p></div><h3>Details</h3><table><tr><th>Workflow ID</th><td>${w.id}</td></tr><tr><th>Company</th><td>${companyName} (${w.companyId})</td></tr><tr><th>Status</th><td>${w.status}</td></tr><tr><th>Created</th><td>${w.createdAt||""}</td></tr></table><h3>Notes</h3>${w.notes?.length?`<table><tr><th>Date</th><th>Note</th></tr>${w.notes.map((n:any)=>`<tr><td>${new Date(n.date).toLocaleString()}</td><td>${n.text}</td></tr>`).join("")}</table>`:"<p>No notes yet</p>"}<p style="margin-top:40px;font-size:11px;color:#888">Generated by Forging Line ERP - ${me?.email}</p></body></html>`
    const win = window.open("","_blank"); win?.document.write(html); win?.document.close(); win?.print()
  }
  const emailWorkflow=(w:any)=>{
    const subject = `Production Sheet - ${w.name} - ${companyName}`
    const body = `Production Sheet\n\nWorkflow: ${w.name}\nCompany: ${companyName}\nStatus: ${w.status}\nID: ${w.id}\nDate: ${new Date().toLocaleString()}\n\nNotes:\n${w.notes?.map((n:any)=>`- ${n.text} (${new Date(n.date).toLocaleDateString()})`).join("\n")||"No notes"}\n\nGenerated by Forging Line ERP\n${me?.email}`
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
  }
  return (
    <div style={{display:"flex", minHeight:"100vh", background:"#f8f9fb", color:"#1a1a1a", fontFamily:"Inter, sans-serif"}}>
      <div style={{width:260, background:"#0f1014", color:"white", padding:24, display:"flex", flexDirection:"column"}}>
        <div style={{fontWeight:900, fontSize:18, letterSpacing:"-0.5px"}}><span style={{color:"#ff7a00"}}>FORGING</span><br/>LINE ERP</div>
        <div style={{marginTop:30, fontSize:12, color:"#888", textTransform:"uppercase", letterSpacing:"1px"}}>Navigation</div>
        <div style={{marginTop:15, display:"grid", gap:6}}>
          <div style={{background:"white", color:"black", padding:"10px 14px", borderRadius:8, fontSize:13, fontWeight:600}}>Dashboard</div>
          <a href="/dashboard/tenants" style={{color:"#aaa", padding:"10px 14px", borderRadius:8, fontSize:13, textDecoration:"none"}}>{isSuper?"Companies":"My Company"}</a>
          <a href="/dashboard/workflows" style={{color:"#aaa", padding:"10px 14px", borderRadius:8, fontSize:13, textDecoration:"none"}}>Workflows</a>
          {isSuper && <a href="/dashboard/users" style={{color:"#aaa", padding:"10px 14px", borderRadius:8, fontSize:13, textDecoration:"none"}}>Users</a>}
        </div>
        <div style={{marginTop:"auto", borderTop:"1px solid #222", paddingTop:20}}>
          <div style={{fontSize:13, fontWeight:600}}>{me?.email}</div>
          <div style={{fontSize:11, color:"#888", marginTop:4}}>{isSuper?`Super Admin`:`${companyName} • ${me?.role}`}</div>
          <div onClick={()=>{localStorage.clear(); location.href="/"}} style={{marginTop:15, fontSize:12, color:"#666", cursor:"pointer", background:"#1a1a1f", padding:"8px 12px", borderRadius:6, textAlign:"center"}}>Sign out</div>
        </div>
      </div>
      <div style={{flex:1, padding:32}}>
        <div style={{display:"flex", justifyContent:"space-between", alignItems:"center"}}>
          <div><h1 style={{margin:0, fontSize:24, fontWeight:700, color:"#0f1014"}}>{isSuper?"Dashboard Overview":`${companyName}`}</h1><p style={{margin:"6px 0 0", color:"#666", fontSize:13}}>{isSuper?`Managing ${tenants.length} companies • ${wfs.length} total workflows`:`Production overview • ${wfs.length} workflows`}</p></div>
          <div style={{display:"flex", gap:10}}>
            <button onClick={()=>{ const allHtml = `<html><head><style>body{font-family:Arial;padding:30px} table{width:100%;border-collapse:collapse} th,td{border:1px solid #ddd;padding:8px} th{background:#f5f5f5}</style></head><body><h1>${companyName} - Production Report</h1><p>Date: ${new Date().toLocaleString()}</p><table><tr><th>Workflow</th><th>Status</th><th>Notes</th></tr>${wfs.map((w:any)=>`<tr><td>${w.name}</td><td>${w.status}</td><td>${w.notes?.length||0}</td></tr>`).join("")}</table></body></html>`; const win=window.open("","_blank"); win?.document.write(allHtml); win?.document.close(); win?.print() }} style={{padding:"10px 16px", background:"#0f1014", color:"white", border:"none", borderRadius:8, fontSize:12, fontWeight:600, cursor:"pointer"}}>🖨️ Print Report</button>
            <button onClick={()=>{ const subject=`Production Report - ${companyName}`; const body=`Report for ${companyName}\nDate: ${new Date().toLocaleString()}\nWorkflows: ${wfs.length}\n\n${wfs.map((w:any)=>`- ${w.name} (${w.status})`).join("\n")}`; window.location.href=`mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}` }} style={{padding:"10px 16px", background:"white", border:"1px solid #ddd", borderRadius:8, fontSize:12, fontWeight:600, cursor:"pointer"}}>📧 Email Report</button>
          </div>
        </div>
        <div style={{display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:16, marginTop:28}}>
          <div style={{background:"white", border:"1px solid #e5e7eb", borderRadius:12, padding:20}}><div style={{fontSize:11, color:"#888", textTransform:"uppercase", letterSpacing:"0.5px"}}>Total Workflows</div><div style={{fontSize:28, fontWeight:700, marginTop:6}}>{wfs.length}</div><div style={{fontSize:12, color:"#666", marginTop:4}}>{isSuper?"Across all companies":"For your company"}</div></div>
          <div style={{background:"white", border:"1px solid #e5e7eb", borderRadius:12, padding:20}}><div style={{fontSize:11, color:"#888", textTransform:"uppercase"}}>In Progress</div><div style={{fontSize:28, fontWeight:700, marginTop:6, color:"#ff7a00"}}>{wfs.filter((w:any)=>w.status==="In Progress").length}</div><div style={{fontSize:12, color:"#666", marginTop:4}}>Active production</div></div>
          <div style={{background:"white", border:"1px solid #e5e7eb", borderRadius:12, padding:20}}><div style={{fontSize:11, color:"#888", textTransform:"uppercase"}}>Completed</div><div style={{fontSize:28, fontWeight:700, marginTop:6, color:"#00a86b"}}>{wfs.filter((w:any)=>w.status==="Completed").length}</div><div style={{fontSize:12, color:"#666", marginTop:4}}>Finished</div></div>
        </div>
        <div style={{marginTop:28, background:"white", border:"1px solid #e5e7eb", borderRadius:12, overflow:"hidden"}}>
          <div style={{padding:"16px 20px", borderBottom:"1px solid #e5e7eb", display:"flex", justifyContent:"space-between", alignItems:"center"}}><div style={{fontWeight:600}}>Production Workflows</div><a href="/dashboard/workflows" style={{fontSize:12, color:"#ff7a00", textDecoration:"none", fontWeight:600}}>Manage all →</a></div>
          {wfs.length===0? <div style={{padding:40, textAlign:"center", color:"#888"}}>No workflows yet. Create your first workflow.</div> :
            wfs.map((w:any)=><div key={w.id} style={{padding:"16px 20px", borderBottom:"1px solid #f0f0f0", display:"flex", justifyContent:"space-between", alignItems:"center"}}>
              <div style={{flex:1}}><div style={{fontWeight:600, fontSize:14}}>{w.name}</div><div style={{fontSize:12, color:"#888", marginTop:3}}>{w.id} • {w.status} {isSuper && `• ${tenants.find((t:any)=>t.id===w.companyId)?.name||w.companyId}`}</div>{w.notes?.length>0 && <div style={{fontSize:11, color:"#555", marginTop:6, background:"#f8f9fb", padding:"6px 10px", borderRadius:6}}>📝 {w.notes[w.notes.length-1].text}</div>}</div>
              <div style={{display:"flex", gap:6, alignItems:"center"}}>
                <input placeholder="Add note..." value={noteText[w.id]||""} onChange={e=>setNoteText({...noteText, [w.id]:e.target.value})} onKeyDown={e=>{if(e.key==="Enter") addNote(w.id)}} style={{padding:"6px 10px", border:"1px solid #e5e7eb", borderRadius:6, fontSize:12, width:160}}/>
                <button onClick={()=>addNote(w.id)} style={{padding:"6px 10px", background:"#f0f0f0", border:"none", borderRadius:6, fontSize:11, cursor:"pointer"}}>Add</button>
                <button onClick={()=>printWorkflow(w)} style={{padding:"6px 10px", background:"#0f1014", color:"white", border:"none", borderRadius:6, fontSize:11, cursor:"pointer"}}>Print</button>
                <button onClick={()=>emailWorkflow(w)} style={{padding:"6px 10px", background:"white", border:"1px solid #ddd", borderRadius:6, fontSize:11, cursor:"pointer"}}>Email</button>
              </div>
            </div>)
          }
        </div>
      </div>
    </div>
  )
}
